export const seachConstants = {
  GET_SEARCH_ITEM_REQUEST: "GET_SEARCH_ITEM_REQUEST",
  GET_SEARCH_ITEM_SUCCESS: "GET_SEARCH_ITEM_SUCCESS",
  GET_SEARCH_ITEM_FAILURE: "GET_SEARCH_ITEM_FAILURE",
};

export const userContants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const JobPostedConstants = {
  JOB_POSTED_REQUEST: "JOB_POSTED_REQUEST",
  JOB_POSTED_SUCCESS: "JOB_POSTED_SUCCESS",
  JOB_POSTED_FAILURE: "JOB_POSTED_FAILURE",
};

export const getJobsPostedBySingleUserConstants = {
  GET_JOB_POSTED_BY_SINGLE_USER_SUCCESS:
    "GET_JOB_POSTED_BY_SINGLE_USER_SUCCESS",
  GET_JOB_POSTED_BY_SINGLE_USER_FAILURE:
    "GET_JOB_POSTED_BY_SINGLE_USER_FAILURE",
};
export const getsinglejobDetail = {
  GET_JOB_DETAIL_REQUEST: "GET_JOB_DETAIL_REQUEST",
  GET_JOB_DETAIL_SUCCESS: "GET_JOB_DETAIL_SUCCESS",
  GET_JOB_DETAIL_FAILURE: "GET_JOB_DETAIL_FAILURE",
};
export const getAllJobs = {
  GET_ALL_JOBS_REQUEST: "GET_ALL_JOBS_REQUEST",
  GET_ALL_JOBS_SUCCESS: "GET_ALL_JOBS_SUCCESS",
  GET_ALL_JOBS_FAILURE: "GET_ALL_JOBS_FAILURE",
};

export const UpdateUser = {
  UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
  RESET_UPDATE_USER:"RESET_UPDATE_USER"
};
export const FILLYOURPROFILE = {
  FILLYOURPROFILE_RESPONSE: "FILLYOURPROFILE_RESPONSE",

};
